import os
from typing import Any

from agent import AgentRole
from tools import ToolRegistry

_LATEX_TEMPLATE = r"""\documentclass[11pt,a4paper]{article}

\usepackage[utf8]{inputenc}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\usepackage{graphicx}
\usepackage{amsmath,amssymb}
\usepackage{enumitem}
\usepackage{titlesec}
\usepackage{fancyhdr}
\usepackage{cite}

\title{%s}
\author{Generated by Universal Multi-Agent Research Framework}
\date{\today}

\begin{document}

\maketitle

\begin{abstract}
%s
\end{abstract}

\tableofcontents
\newpage

__CONTENT_PLACEHOLDER__

\section{Scoring Summary}
The following table summarizes the evaluation scores for the top-ranked research proposals.
Each proposal was scored on five dimensions (1--10 scale): depth, accuracy, relevance, clarity, and originality.

__SCORES_PLACEHOLDER__

\bibliographystyle{plain}
\begin{thebibliography}{99}

__BIB_PLACEHOLDER__

\end{thebibliography}

\end{document}
"""


class WriterRole(AgentRole):
    """Generate a LaTeX research proposal from the top-scored submissions."""

    agent_name = "writer"
    max_steps = 12

    def tools_for_backend(self, backend: str) -> list[dict[str, Any]]:
        return ToolRegistry.to_dicts(ToolRegistry.writer_tools())

    def build_task(self, backend: str, topic: str = "",
                   scored_works: list[dict[str, Any]] | None = None, **context: Any) -> str:
        assert scored_works is not None
        # Show all works with their scores so the writer can decide what to include
        file_list = "\n".join(
            f"  - Rank {i+1} (score {s.get('total_score', '?')}/50): {s['output_file']} — {s['title']}"
            for i, s in enumerate(scored_works)
        )

        return f"""You are a LaTeX document generator for a research proposal. Generate a complete, publication-quality LaTeX document.

## Research Topic
{topic}

## Scored Research Works (all available)
{file_list}

## Instructions
1. Read ALL of the research output files listed above using `read_file`. You have access to every scored work — not just the top few.
2. Synthesize the findings into well-structured LaTeX sections (`\\section{{...}}`) that together form a coherent proposal. Use proper LaTeX formatting:
   - `\\subsection{{...}}` for sub-topics
   - `\\textbf{{...}}` and `\\textit{{...}}` for emphasis
   - `itemize` or `enumerate` for lists
   - `\\begin{{quote}}...\\end{{quote}}` for key insights
   - Math mode `$...$` or `$$...$$` where appropriate
3. You decide which works to emphasize and how to organize the proposal — include the most relevant findings from each work. Works with higher scores are generally more reliable, but lower-scored works may contain essential material (e.g., error bounds, position encoding) that the proposal needs.
4. Write an abstract (150-250 words) summarizing the proposal and its contribution to the main topic.
5. Write a scoring summary section with a table showing scores for each dimension across all works.
6. Include a bibliography section with references from the research.
7. Use `write_file` to save the FULL LaTeX document to `research_proposal.tex`.
8. Output TASK_COMPLETE when done.

IMPORTANT: Generate the COMPLETE LaTeX document with preamble and all sections. The document MUST compile with pdflatex. Use proper LaTeX escaping for special characters (&, %, $, #, _, {{, }}, ~, ^, \\)."""

    def parse_result(self, result, working_dir: str, topic: str = "",
                     scored_works: list[dict[str, Any]] | None = None, **context: Any) -> str:
        assert scored_works is not None
        tex_path = os.path.join(working_dir, "research_proposal.tex")
        if os.path.exists(tex_path):
            return tex_path
        return _fallback_latex(scored_works, topic, working_dir)


def write_proposal(
    scored_works: list[dict[str, Any]],
    topic: str,
    working_dir: str,
    backend: str = "deepseek",
    version: int = 1,
) -> str:
    """Generate a LaTeX research proposal from scored research submissions.

    Args:
        scored_works: All scored items from the reviewer (sorted by rank), each
                      with sub_task_id, title, output_file, scores, total_score, rank.
        topic: Original research topic for the document title.
        working_dir: Working directory for file operations.
        backend: LLM backend.
        version: checkpoint version.

    Returns:
        Path to the generated LaTeX file.
    """
    if not scored_works:
        return ""

    role = WriterRole()
    return role.execute(
        working_dir=working_dir,
        backend=backend,
        version=version,
        topic=topic,
        scored_works=scored_works,
    )


_LATEX_ESCAPE_MAP = {
    "\\": r"\textbackslash ",
    "~": r"\textasciitilde ",
    "^": r"\textasciicircum ",
}


def _latex_escape(text: str) -> str:
    """Escape LaTeX special characters in user-provided text."""
    for char in ("\\", "{", "}", "$", "&", "#", "_", "%", "~", "^"):
        text = text.replace(char, _LATEX_ESCAPE_MAP.get(char, "\\" + char))
    return text


def _fallback_latex(
    scored_works: list[dict[str, Any]],
    topic: str,
    working_dir: str,
) -> str:
    """Generate a basic LaTeX file using the template."""
    n = len(scored_works)
    abstract = (
        f"This document presents the research proposals on {_latex_escape(topic)}, "
        f"generated by a multi-agent research framework. {n} research "
        f"agents investigated distinct sub-topics, which were then scored by a "
        f"reviewer agent on depth, accuracy, relevance, clarity, and originality. "
        f"The scored proposals are presented here."
    )

    # Build content sections
    sections = []
    for item in scored_works:
        title = item.get("title", "Untitled")
        scores = item.get("scores", {})
        sections.append(r"\section{" + _latex_escape(title) + "}")
        sections.append(
            r"\textbf{Score: " + str(item.get("total_score", 0))
            + "/50} \hfill \textbf{Rank: " + str(item.get("rank", "?")) + "}"
        )
        sections.append("")
        sections.append(
            "\\textit{Full research content is available in the accompanying file: "
            + item.get("output_file", "unknown") + "}"
        )
        sections.append("")

    # Build scores table
    score_rows = []
    for item in scored_works:
        title = _latex_escape(item.get("title", "Untitled")[:40])
        s = item.get("scores", {})
        score_rows.append(
            f"  {title} & {s.get('depth', '-')} & {s.get('accuracy', '-')} & "
            f"{s.get('relevance', '-')} & {s.get('clarity', '-')} & "
            f"{s.get('originality', '-')} & {item.get('total_score', '-')} \\\\"
        )

    scores_table = (
        r"\begin{table}[h]" + "\n"
        r"\centering" + "\n"
        r"\begin{tabular}{|l|c|c|c|c|c|c|}" + "\n"
        r"\hline" + "\n"
        r"\textbf{Proposal} & \textbf{Depth} & \textbf{Accuracy} & "
        r"\textbf{Relevance} & \textbf{Clarity} & \textbf{Originality} & "
        r"\textbf{Total} \\" + "\n"
        r"\hline" + "\n"
        + "\n".join(score_rows) + "\n"
        r"\hline" + "\n"
        r"\end{tabular}" + "\n"
        r"\caption{Scoring breakdown for research proposals (each dimension scored 1--10)}" + "\n"
        r"\end{table}"
    )

    bib_entries = []
    for i, item in enumerate(scored_works):
        bib_entries.append(
            r"\bibitem{research" + str(i+1) + "} "
            + f"Research Agent {i+1}, ``{_latex_escape(item.get('title', 'Untitled'))},'' "
            + r"Universal Multi-Agent Framework, \today."
        )

    document = _LATEX_TEMPLATE % (_latex_escape(topic), abstract)
    document = document.replace("__CONTENT_PLACEHOLDER__", "\n".join(sections))
    document = document.replace("__SCORES_PLACEHOLDER__", scores_table)
    document = document.replace("__BIB_PLACEHOLDER__", "\n".join(bib_entries))

    tex_path = os.path.join(working_dir, "research_proposal.tex")
    with open(tex_path, "w") as f:
        f.write(document)

    return tex_path
