from typing import Any

from agent import run_agent
from tools import TOOL_MAP

WRITER_TOOLS = [
    {
        "name": "read_file",
        "description": "Read a file. Use to read each top-ranked research output.",
        "parameters": {"path": "str"},
    },
    {
        "name": "write_file",
        "description": "Write content to a file. Use to save the LaTeX document.",
        "parameters": {"path": "str", "content": "str"},
    },
]

_LATEX_TEMPLATE = r"""\documentclass[11pt,a4paper]{article}

\usepackage[utf8]{inputenc}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\usepackage{graphicx}
\usepackage{amsmath,amssymb}
\usepackage{enumitem}
\usepackage{titlesec}
\usepackage{fancyhdr}
\usepackage{cite}

\title{%s}
\author{Generated by Universal Multi-Agent Research Framework}
\date{\today}

\begin{document}

\maketitle

\begin{abstract}
%s
\end{abstract}

\tableofcontents
\newpage

__CONTENT_PLACEHOLDER__

\section{Scoring Summary}
The following table summarizes the evaluation scores for the top-ranked research proposals.
Each proposal was scored on five dimensions (1--10 scale): depth, accuracy, relevance, clarity, and originality.

__SCORES_PLACEHOLDER__

\bibliographystyle{plain}
\begin{thebibliography}{99}

__BIB_PLACEHOLDER__

\end{thebibliography}

\end{document}
"""


def write_proposal(
    top_3: list[dict[str, Any]],
    topic: str,
    working_dir: str,
    backend: str = "deepseek",
) -> str:
    """Generate a LaTeX research proposal from the top 3 scored submissions.

    Args:
        top_3: Top 3 scored items (from reviewer), each with sub_task_id, title,
               output_file, scores, total_score, rank.
        topic: Original research topic for the document title.
        working_dir: Working directory for file operations.
        backend: LLM backend.

    Returns:
        Path to the generated LaTeX file.
    """
    if not top_3:
        return ""

    file_list = "\n".join(
        f"  - Rank {i+1} (score {s['total_score']}/50): {s['output_file']} — {s['title']}"
        for i, s in enumerate(top_3)
    )

    task = f"""You are a LaTeX document generator for a research proposal. Generate a complete, publication-quality LaTeX document.

## Research Topic
{topic}

## Top 3 Ranked Research Proposals
{file_list}

## Instructions
1. Read each of the top 3 research output files using `read_file`.
2. For each proposal, write a well-structured LaTeX section (`\\section{{...}}`) synthesizing the research findings. Use proper LaTeX formatting:
   - `\\subsection{{...}}` for sub-topics
   - `\\textbf{{...}}` and `\\textit{{...}}` for emphasis
   - `itemize` or `enumerate` for lists
   - `\\begin{{quote}}...\\end{{quote}}` for key insights
   - Math mode `$...$` or `$$...$$` where appropriate
3. Write an abstract (150-250 words) summarizing all three proposals and their contribution to the main topic.
4. Write a scoring summary section with a table showing scores for each dimension.
5. Include a bibliography section with placeholder references from the research.
6. Use `write_file` to save the FULL LaTeX document to `research_proposal.tex`.
7. Output TASK_COMPLETE when done.

IMPORTANT: Generate the COMPLETE LaTeX document with preamble and all sections. The document MUST compile with pdflatex. Use proper LaTeX escaping for special characters (&, %, $, #, _, {{, }}, ~, ^, \\)."""

    run_agent(
        task=task,
        working_dir=working_dir,
        tools=WRITER_TOOLS,
        tool_map=TOOL_MAP,
        max_steps=12,
        backend=backend,
    )

    import os

    tex_path = os.path.join(working_dir, "research_proposal.tex")
    if os.path.exists(tex_path):
        return tex_path

    # Fallback: generate a basic LaTeX from template
    return _fallback_latex(top_3, topic, working_dir)


def _latex_escape(text: str) -> str:
    """Escape LaTeX special characters in user-provided text."""
    for char in ("\\", "{", "}", "$", "&", "#", "_", "%", "~", "^"):
        if char == "\\":
            text = text.replace("\\", "\\textbackslash ")
        elif char == "~":
            text = text.replace("~", "\\textasciitilde ")
        elif char == "^":
            text = text.replace("^", "\\textasciicircum ")
        else:
            text = text.replace(char, "\\" + char)
    return text


def _fallback_latex(
    top_3: list[dict[str, Any]],
    topic: str,
    working_dir: str,
) -> str:
    """Generate a basic LaTeX file using the template."""
    import os

    abstract = (
        f"This document presents the top-ranked research proposals on {_latex_escape(topic)}, "
        f"generated by a multi-agent research framework. Three independent research "
        f"agents investigated distinct sub-topics, which were then scored by a "
        f"reviewer agent on depth, accuracy, relevance, clarity, and originality. "
        f"The highest-scored proposals are presented here."
    )

    # Build content sections
    sections = []
    for item in top_3:
        title = item.get("title", "Untitled")
        scores = item.get("scores", {})
        sections.append(r"\section{" + _latex_escape(title) + "}")
        sections.append(
            r"\textbf{Score: " + str(item.get("total_score", 0))
            + "/50} \hfill \textbf{Rank: " + str(item.get("rank", "?")) + "}"
        )
        sections.append("")
        sections.append(
            "\\textit{Full research content is available in the accompanying file: "
            + item.get("output_file", "unknown") + "}"
        )
        sections.append("")

    # Build scores table
    score_rows = []
    for item in top_3:
        title = _latex_escape(item.get("title", "Untitled")[:40])
        s = item.get("scores", {})
        score_rows.append(
            f"  {title} & {s.get('depth', '-')} & {s.get('accuracy', '-')} & "
            f"{s.get('relevance', '-')} & {s.get('clarity', '-')} & "
            f"{s.get('originality', '-')} & {item.get('total_score', '-')} \\\\"
        )

    scores_table = (
        r"\begin{table}[h]" + "\n"
        r"\centering" + "\n"
        r"\begin{tabular}{|l|c|c|c|c|c|c|}" + "\n"
        r"\hline" + "\n"
        r"\textbf{Proposal} & \textbf{Depth} & \textbf{Accuracy} & "
        r"\textbf{Relevance} & \textbf{Clarity} & \textbf{Originality} & "
        r"\textbf{Total} \\" + "\n"
        r"\hline" + "\n"
        + "\n".join(score_rows) + "\n"
        r"\hline" + "\n"
        r"\end{tabular}" + "\n"
        r"\caption{Scoring breakdown for top-ranked research proposals (each dimension scored 1--10)}" + "\n"
        r"\end{table}"
    )

    bib_entries = []
    for i, item in enumerate(top_3):
        bib_entries.append(
            r"\bibitem{research" + str(i+1) + "} "
            + f"Research Agent {i+1}, ``{_latex_escape(item.get('title', 'Untitled'))},'' "
            + r"Universal Multi-Agent Framework, \today."
        )

    document = _LATEX_TEMPLATE % (_latex_escape(topic), abstract)
    document = document.replace("__CONTENT_PLACEHOLDER__", "\n".join(sections))
    document = document.replace("__SCORES_PLACEHOLDER__", scores_table)
    document = document.replace("__BIB_PLACEHOLDER__", "\n".join(bib_entries))

    tex_path = os.path.join(working_dir, "research_proposal.tex")
    with open(tex_path, "w") as f:
        f.write(document)

    return tex_path
